package com.example.googleads_test_app.googleads_oauth_creds_gen.controller;

import com.example.googleads_test_app.googleads_oauth_creds_gen.utils.OAuthConfig;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class AuthorizationController {

    private final OAuthConfig oAuthConfig;

    @Autowired
    public AuthorizationController(OAuthConfig oAuthConfig) {
        this.oAuthConfig = oAuthConfig;
    }

    /*
    *  This method is called by the Google's Authorization server after the user
    *  has authorized the application to access their Google Ads account.
    *       - The authorization code is used to generate OAuth credentials.
    *       - The authorization code is generated by the Google's Authorization server.
    *
    * */
    @GetMapping("/oauth2callback")
    public void getOAuthCreds(@RequestParam String state, @RequestParam String code, @RequestParam String scope) {
        System.out.println("state: " + state);
        System.out.println("code: " + code);
        System.out.println("scope: " + scope);

        // Set the authorization code, state, and scope in the OAuthConfig bean.
        oAuthConfig.setAuthorizationCode(code);
        oAuthConfig.setState(state);
        oAuthConfig.setScope(scope);
    }
}
